apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "landingChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "landingChart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "landingChart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "landingChart.serviceAccountName" . }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.container.portName }}
              containerPort: {{ .Values.container.port }}
          env:
            - name: NEXT_PUBLIC_RECAPTCHA_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: NEXT_PUBLIC_RECAPTCHA_SITE_KEY
            - name: NEXT_PUBLIC_EVERCODE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: NEXT_PUBLIC_EVERCODE_API_URL
            - name: NEXT_PUBLIC_CHANGENOW_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: NEXT_PUBLIC_CHANGENOW_API_URL
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: PORT
            - name: NEXT_TELEMETRY_DISABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: NEXT_TELEMETRY_DISABLED
