{{- $svcName := .Values.service.name -}}
{{- $svcPort  := .Values.service.port -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: {{ .Values.issuer.name }}
  labels:
    {{- include "landingChart.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
        {{- range $index, $host := .Values.ingress.hosts }}
        - {{ $host }}
        {{- end }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    {{- range $index, $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
