apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerConfigJson }}
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
