apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "landingChart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.portName }}
      name: http
      protocol: TCP
  selector:
    {{- include "landingChart.selectorLabels" . | nindent 4 }}
