name: Deploy new version of application

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check repo
        uses: actions/checkout@v2

      - name: Set image name variable
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)
          version=$(echo "$timestamp" | sed -E 's/(.*)/v\1/')
          prefix="dev-"
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            prefix="prod-"
          fi
          echo "IMAGE_NAME=${prefix}cherryswap_$version" >> $GITHUB_ENV

      - name: Build images
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Save image to tar
        run: docker save ${{ env.IMAGE_NAME }} -o "${{ env.IMAGE_NAME }}.tar"

      - name: Upload tar file
        uses: actions/upload-artifact@v2
        with:
          name: '${{ env.IMAGE_NAME }}.tar'
          path: '${{ env.IMAGE_NAME }}.tar'

      - name: Connect to server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download tar file
        uses: actions/download-artifact@v2
        with:
          name: '${{ env.IMAGE_NAME }}.tar'
          path: ~/images/"${{ env.IMAGE_NAME }}.tar"
